codecov:
  notify:
    require_ci_to_pass: yes

coverage: 
  precision: 4
  round: down
  range: "65...90"

  status:
    project:
      default: 
        threshold: 0.2
    patch:
      default: 
        target: 0%
    changes: 100

parsers:
  gcov:
    branch_detection:
      condition: yees
      loop: yes
      method: no
      macro: no

commen: 
  layout: "header, diff"
  behavior: default
  require_changes: no

ignore: 
  - 'LICENSE'
  - '*.git'
  - '*.md'
  - '*.yaml'
  - '*.yml'
