version: 2

jobs:
  build:
    docker:
      - image: rust:latest
    steps:
      - checkout
      - restore_cache:
          key: ibis-cache
      - run:
          name: Check formatting
          command: cargo fmt -- --check
      - run:
          name: Stable Build
          command: cargo build
      - run:
          name: Test
          command: cargo test
      - save_cache:
          key: ibis-cache
          paths:
            - "~/.cargo"
            - "./target"
